### ISSUE TITLE
Log file not generating

### ISSUE THREAD

**Issue by shubhanshu02** [bytewax/bytewax-clickhouse#14]
Since this library is calling the `logging.basicConfig()` as in the snippet below, this is causing the basic config from calling script to be overridden by this configuration and hence log files are not being generated.

https://github.com/bytewax/bytewax-clickhouse/blob/119d8b784655531546ba054dbb9d23344cc73fa8/src/bytewax/clickhouse/__init__.py#L45-L47

Ideally, the caller should be responsible for setting the basic configuration for logging, and if it isn't configured then only the library should try to configure it. This is because the subsequent calls to the `logging.basicConfig()` are ignored.

**Comment by awmatheson** [comment]
fixed in #30
